# Generated by Django 2.0.2 on 2018-02-19 23:45

from django.db import migrations, models
import lecture.models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_lectureapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=lecture.models.poster_upload_path, verbose_name='Poster'),
        ),
    ]
