# Generated by Django 2.0.2 on 2018-10-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_lecture_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='external_registration_url',
            field=models.URLField(blank=True, null=True, verbose_name='External Registration URL'),
        ),
    ]
