# Generated by Django 2.0.2 on 2018-02-19 20:25

import common.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', common.managers.UserManager()),
            ],
        ),
    ]
