# Generated by Django 2.0.2 on 2018-02-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180220_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Turkish'), ('ru', 'Russian')], default='tr', max_length=10),
        ),
    ]
