# Generated by Django 2.0.2 on 2018-02-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_user_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number'),
        ),
    ]
