# Generated by Django 2.0.2 on 2018-02-26 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20180226_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9055555'. Up to 16 digits allowed.", regex='^\\+?1?\\d{7,16}$')], verbose_name='Phone Number'),
        ),
    ]
